import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { eq } from "drizzle-orm";
import {
  createDatabaseContext,
  closeDatabaseConnections,
  type DatabaseContext,
} from "../src/client";
import { runMigrations } from "../src/migrate";
import {
  tenants,
  users,
  subjects,
  chapters,
  topics,
  ingestionJobs,
  questionDrafts,
  userTopicMetrics,
  userAnalytics,
} from "../src/schema/index";
import {
  safeParseQuestionDraft,
  PercentageRateSchema,
  UserTopicMetricsSchema,
} from "@admission-engine/types";
import { atomicIncrementUserAnalytics } from "../src/analytics-upsert";

describe("Admission Exam Engine - Database Schema & Constraints Test Suite", () => {
  let ctx: DatabaseContext;

  beforeAll(async () => {
    // Create an isolated in-memory PostgreSQL WASM instance
    ctx = createDatabaseContext({ usePglite: true });
  });

  afterAll(async () => {
    await closeDatabaseConnections();
  });

  it("1. Executes Drizzle migrations against PostgreSQL; asserts clean termination with exit code 0", async () => {
    // Execute DDL migrations generated by drizzle-kit
    await expect(runMigrations(ctx)).resolves.not.toThrow();

    // Verify critical tables exist in PostgreSQL information_schema
    const tablesQuery = await ctx.db.execute<{ table_name: string }>(
      `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;`
    );

    const tableNames = tablesQuery.rows.map((row) => row.table_name);
    expect(tableNames).toContain("tenants");
    expect(tableNames).toContain("users");
    expect(tableNames).toContain("questions");
    expect(tableNames).toContain("ingestion_jobs");
    expect(tableNames).toContain("question_drafts");
    expect(tableNames).toContain("exams");
    expect(tableNames).toContain("exam_submissions");
    expect(tableNames).toContain("submission_answers");
    expect(tableNames).toContain("mistake_book");
    expect(tableNames).toContain("user_analytics");
    expect(tableNames).toContain("user_topic_metrics");
  });

  it("2. Validates that question_drafts correctly links to ingestion_jobs with CASCADE delete", async () => {
    const db = ctx.db;

    // Create required dependencies: tenant, user (admin), subject, chapter
    await db.insert(tenants).values({
      id: "DIRECT_B2C",
      name: "Direct B2C Admission Students",
      slug: "direct-b2c",
    }).onConflictDoNothing();

    const adminId = "11111111-1111-1111-1111-111111111111";
    await db.insert(users).values({
      id: adminId,
      tenantId: "DIRECT_B2C",
      role: "SUPER_ADMIN",
      email: "ocr_admin@test.com",
      fullName: "OCR Admin",
    }).onConflictDoNothing();

    const [subj] = await db.insert(subjects).values({
      name: "Test Physics",
      code: "TEST_PHY",
      slug: "test-physics",
    }).returning();

    if (!subj) throw new Error("Failed to insert subject");

    const [chap] = await db.insert(chapters).values({
      subjectId: subj.id,
      name: "Test Chapter",
      chapterNumber: 1,
      slug: "test-chapter",
    }).returning();

    if (!chap) throw new Error("Failed to insert chapter");

    // Insert Ingestion Job
    const jobId = "job_123e4567-e89b-12d3-a456-426614174000";
    await db.insert(ingestionJobs).values({
      id: jobId,
      adminId,
      sourceFileUrl: "https://storage.platform.com/uploads/physics_buet_2022.pdf",
      fileType: "PDF",
      targetSubjectId: subj.id,
      targetChapterId: chap.id,
      status: "PROCESSING",
      totalDetected: 2,
      approvedCount: 0,
      rejectedCount: 0,
    });

    // Insert 2 question drafts linked to the job
    const draftId1 = "22222222-2222-2222-2222-222222222221";
    const draftId2 = "22222222-2222-2222-2222-222222222222";

    await db.insert(questionDrafts).values([
      {
        id: draftId1,
        jobId,
        parsedQuestionText: "Draft question 1 with $E = mc^2$",
        status: "DRAFT",
        parsedOptions: [
          { id: "A", text: "$mc^2$" },
          { id: "B", text: "$mc$" },
        ],
        parsedCorrectOption: "A",
      },
      {
        id: draftId2,
        jobId,
        parsedQuestionText: "Draft question 2 with $F = ma$",
        status: "DRAFT",
        parsedOptions: [
          { id: "A", text: "$ma$" },
          { id: "B", text: "$mg$" },
        ],
        parsedCorrectOption: "A",
      },
    ]);

    // Verify drafts exist
    const draftsBeforeDelete = await db
      .select()
      .from(questionDrafts)
      .where(eq(questionDrafts.jobId, jobId));
    expect(draftsBeforeDelete).toHaveLength(2);

    // Delete the parent ingestion job
    await db.delete(ingestionJobs).where(eq(ingestionJobs.id, jobId));

    // Assert CASCADE delete: drafts must be automatically deleted
    const draftsAfterDelete = await db
      .select()
      .from(questionDrafts)
      .where(eq(questionDrafts.jobId, jobId));
    expect(draftsAfterDelete).toHaveLength(0);
  });

  it("3. Verifies that user_topic_metrics rejects accuracy rates greater than 100.00 via CHECK constraint & Zod", async () => {
    const db = ctx.db;

    const studentId = "33333333-3333-3333-3333-333333333333";
    await db.insert(users).values({
      id: studentId,
      tenantId: "DIRECT_B2C",
      role: "STUDENT",
      email: "student_metrics@test.com",
      fullName: "Metrics Student",
    }).onConflictDoNothing();

    const [subj] = await db.insert(subjects).values({
      name: "Metrics Subject",
      code: "MET_SUBJ",
      slug: "met-subj",
    }).returning();

    const [chap] = await db.insert(chapters).values({
      subjectId: subj!.id,
      name: "Metrics Chapter",
      chapterNumber: 1,
      slug: "met-chap",
    }).returning();

    const [top] = await db.insert(topics).values({
      chapterId: chap!.id,
      name: "Metrics Topic",
      slug: "met-topic",
    }).returning();

    const topicId = top!.id;

    // Test 3a: PostgreSQL CHECK constraint rejects accuracy_rate > 100.00
    await expect(
      db.insert(userTopicMetrics).values({
        userId: studentId,
        topicId,
        totalAttempted: 10,
        totalCorrect: 12,
        accuracyRate: "120.00", // Invalid: exceeds 100.00
        masteryScore: "50.00",
      })
    ).rejects.toThrow();

    // Test 3b: PostgreSQL CHECK constraint rejects negative accuracy_rate < 0.00
    await expect(
      db.insert(userTopicMetrics).values({
        userId: studentId,
        topicId,
        totalAttempted: 10,
        totalCorrect: 0,
        accuracyRate: "-5.00", // Invalid: negative
        masteryScore: "50.00",
      })
    ).rejects.toThrow();

    // Test 3c: Valid accuracy_rate within [0.00, 100.00] succeeds
    const [validMetric] = await db
      .insert(userTopicMetrics)
      .values({
        userId: studentId,
        topicId,
        totalAttempted: 20,
        totalCorrect: 18,
        accuracyRate: "90.00",
        masteryScore: "85.50",
      })
      .returning();

    expect(validMetric).toBeDefined();
    expect(validMetric?.accuracyRate).toBe("90.00");
    expect(validMetric?.masteryScore).toBe("85.50");

    // Test 3d: Verify Zod PercentageRateSchema rejects > 100.00
    expect(() => PercentageRateSchema.parse("105.00")).toThrow();
    expect(() => PercentageRateSchema.parse("-1.00")).toThrow();
    expect(PercentageRateSchema.parse("100.00")).toBe("100.00");
    expect(PercentageRateSchema.parse("0.00")).toBe("0.00");
    expect(PercentageRateSchema.parse("87.50")).toBe("87.50");

    // Test 3e: Verify UserTopicMetricsSchema rejects invalid accuracy
    const invalidTopicPayload = {
      id: "44444444-4444-4444-4444-444444444444",
      userId: studentId,
      topicId,
      totalAttempted: 5,
      totalCorrect: 6,
      accuracyRate: "120.00",
      masteryScore: "50.00",
      lastAttemptedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    expect(() => UserTopicMetricsSchema.parse(invalidTopicPayload)).toThrow();
  });

  it("4. Safely parses OCR Vision payloads; catches corrupt JSON & stores FAILED_PARSE without crashing", async () => {
    const db = ctx.db;

    // 4a. Simulate corrupt JSON payload from Vision API (e.g. malformed LaTeX / unescaped brackets)
    const corruptOcrPayload = `{ "parsedQuestionText": "What is the limit \\frac{sin x}{x} as x -> 0?", "parsedOptions": [ INVALID_JSON_ARRAY }`;

    const parseResult = safeParseQuestionDraft(corruptOcrPayload);
    expect(parseResult.success).toBe(false);
    expect(parseResult.status).toBe("FAILED_PARSE");
    expect(parseResult.rawResponse).toBe(corruptOcrPayload);

    // Need an ingestion job for foreign key
    const adminId = "11111111-1111-1111-1111-111111111111";
    const [sub] = await db.select().from(subjects).limit(1);
    const [chap] = await db.select().from(chapters).limit(1);

    const safeJobId = "job_corrupt_ocr_test";
    await db.insert(ingestionJobs).values({
      id: safeJobId,
      adminId,
      sourceFileUrl: "https://storage.platform.com/uploads/corrupt_scan.pdf",
      fileType: "PDF",
      targetSubjectId: sub!.id,
      targetChapterId: chap!.id,
      status: "PROCESSING",
    });

    // 4b. Insert failed parse into database preserving raw_response for manual admin review
    const failedDraftId = "55555555-5555-5555-5555-555555555555";
    const [insertedDraft] = await db
      .insert(questionDrafts)
      .values({
        id: failedDraftId,
        jobId: safeJobId,
        rawResponse: parseResult.rawResponse,
        status: "FAILED_PARSE",
      })
      .returning();

    expect(insertedDraft).toBeDefined();
    expect(insertedDraft?.status).toBe("FAILED_PARSE");
    expect(insertedDraft?.rawResponse).toContain("INVALID_JSON_ARRAY");
  });

  it("5. Executes atomic PostgreSQL upsert queries on user_analytics without race conditions", async () => {
    const db = ctx.db;

    const studentId = "66666666-6666-6666-6666-666666666666";
    await db.insert(users).values({
      id: studentId,
      tenantId: "DIRECT_B2C",
      role: "STUDENT",
      email: "analytics_student@test.com",
      fullName: "Analytics Student",
    }).onConflictDoNothing();

    // 1st exam submission: 10 questions attempted, 8 correct, 600 seconds
    await atomicIncrementUserAnalytics(db, {
      userId: studentId,
      examsTakenIncrement: 1,
      questionsAttemptedIncrement: 10,
      questionsCorrectIncrement: 8,
      studyTimeSecondsIncrement: 600,
    });

    let [analyticsRecord] = await db
      .select()
      .from(userAnalytics)
      .where(eq(userAnalytics.userId, studentId));

    expect(analyticsRecord?.totalExamsTaken).toBe(1);
    expect(analyticsRecord?.totalQuestionsAttempted).toBe(10);
    expect(analyticsRecord?.totalQuestionsCorrect).toBe(8);
    expect(analyticsRecord?.overallAccuracy).toBe("80.00");
    expect(analyticsRecord?.totalStudyTimeSeconds).toBe(600);

    // 2nd exam submission concurrently/atomically: 10 questions attempted, 10 correct, 500 seconds
    await atomicIncrementUserAnalytics(db, {
      userId: studentId,
      examsTakenIncrement: 1,
      questionsAttemptedIncrement: 10,
      questionsCorrectIncrement: 10,
      studyTimeSecondsIncrement: 500,
    });

    [analyticsRecord] = await db
      .select()
      .from(userAnalytics)
      .where(eq(userAnalytics.userId, studentId));

    expect(analyticsRecord?.totalExamsTaken).toBe(2);
    expect(analyticsRecord?.totalQuestionsAttempted).toBe(20);
    expect(analyticsRecord?.totalQuestionsCorrect).toBe(18);
    // (18 / 20) * 100 = 90.00%
    expect(analyticsRecord?.overallAccuracy).toBe("90.00");
    expect(analyticsRecord?.totalStudyTimeSeconds).toBe(1100);
  });
});
